esphome:
  name: air_master
  comment: "Monitor Air Master AM7 Plus sensors with ESP8266 and ESPHome"

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

uart:
  id: uart_bus
  tx_pin: D8  # GPIO15
  rx_pin: D7  # GPIO13
  baud_rate: 19200

output:
  - platform: gpio
    pin: D4  # GPIO2 (often used for onboard LEDs)
    id: led_gpio

external_components:
  - source:
      type: git
      url: https://github.com/SergiySeletsky/air-master-am7-esphome@main

sensor:
  - platform: custom
    lambda: |-
      auto air_master_sensor = new AirMasterSensor(id(uart_bus), id(led_gpio));
      App.register_component(air_master_sensor);
      return {air_master_sensor->pm25_sensor, air_master_sensor->pm10_sensor, air_master_sensor->hcho_sensor, air_master_sensor->tvoc_sensor, air_master_sensor->co2_sensor, air_master_sensor->temperature_sensor, air_master_sensor->humidity_sensor, air_master_sensor->ppm03_sensor, air_master_sensor->ppm05_sensor, air_master_sensor->ppm1_sensor, air_master_sensor->ppm2_sensor, air_master_sensor->ppm5_sensor, air_master_sensor->ppm10_sensor};
    sensors:
    - name: "PM2.5"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 2
      id: pm25_sensor
    - name: "PM10"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 2
      id: pm10_sensor
    - name: "HCHO"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 2
      id: hcho_sensor
    - name: "TVOC"
      unit_of_measurement: "µg/m³"
      accuracy_decimals: 2
      id: tvoc_sensor
    - name: "CO2"
      unit_of_measurement: "ppm"
      accuracy_decimals: 2
      id: co2_sensor
    - name: "Temperature"
      unit_of_measurement: "°C"
      accuracy_decimals: 2
      id: temperature_sensor
    - name: "Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 2
      id: humidity_sensor
    - name: "PPM0.3"
      unit_of_measurement: "ppm"
      accuracy_decimals: 0
      id: ppm03_sensor
    - name: "PPM0.5"
      unit_of_measurement: "ppm"
      accuracy_decimals: 0
      id: ppm05_sensor
    - name: "PPM1.0"
      unit_of_measurement: "ppm"
      accuracy_decimals: 0
      id: ppm1_sensor
    - name: "PPM2.5"
      unit_of_measurement: "ppm"
      accuracy_decimals: 0
      id: ppm2_sensor
    - name: "PPM5.0"
      unit_of_measurement: "ppm"
      accuracy_decimals: 0
      id: ppm5_sensor
    - name: "PPM10"
      unit_of_measurement: "ppm"
      accuracy_decimals: 0
      id: ppm10_sensor