esphome:
  name: air-master
  friendly_name: air_master
  comment: "Monitor Air Master AM7 Plus sensors with ESP8266 and ESPHome"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Sjavaj64eK3MbnpJriE4Lgc97VVZ2d6rx1p8XcXEOYU="

ota:
  password: "900d7930ec4e7655637c848ee6248e87"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Master Fallback Hotspot"
    password: "MvpWAcat0J5P"

captive_portal:

uart:
  id: uart_bus
  tx_pin: D8  # GPIO15
  rx_pin: D7  # GPIO13
  baud_rate: 19200

output:
  - platform: gpio
    pin: D4  # GPIO2 (often used for onboard LEDs)
    id: led_output

external_components:
  - source:
      type: git
      url: https://github.com/SergiySeletsky/air-master-am7-esphome
      ref: main
    components: [airmaster]
    refresh: 60s

sensor:
  - platform: airmaster
    pm25_sensor:
      name: "PM2.5"
    pm10_sensor:
      name: "PM10"
    hcho_sensor:
      name: "HCHO"
    tvoc_sensor:
      name: "TVOC"
    co2_sensor:
      name: "CO2"
    temperature_sensor:
      name: "Temperature"
    humidity_sensor:
      name: "Humidity"
    ppm03_sensor:
      name: "PPM0.3"
    ppm05_sensor:
      name: "PPM0.5"
    ppm1_sensor:
      name: "PPM1.0"
    ppm2_sensor:
      name: "PPM2.5"
    ppm5_sensor:
      name: "PPM5.0"
    ppm10_sensor:
      name: "PPM10"