esphome:
  name: air-master
  friendly_name: Air Master
  comment: "Monitor Air Master AM7 Plus sensors with ESP8266 and ESPHome"

esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Air-Master Fallback Hotspot"
    password: "MvpWAcat0J5P"

captive_portal:

uart:
  id: uart_bus
  tx_pin: TX  # GPIO1
  rx_pin: RX  # GPIO3
  baud_rate: 19200

external_components:
  - source:
      type: git
      url: https://github.com/SergiySeletsky/air-master-esphome
      ref: main
    components: [airmaster]
    refresh: 60s

sensor:
  - platform: airmaster
    pm25_sensor:
      name: "PM2.5"
    pm10_sensor:
      name: "PM10"
    hcho_sensor:
      name: "HCHO"
    tvoc_sensor:
      name: "TVOC"
    co2_sensor:
      name: "CO2"
    temperature_sensor:
      name: "Temperature"
    humidity_sensor:
      name: "Humidity"
    ppm03_sensor:
      name: "PPM0.3"
    ppm05_sensor:
      name: "PPM0.5"
    ppm1_sensor:
      name: "PPM1.0"
    ppm25_sensor:
      name: "PPM2.5"
    ppm5_sensor:
      name: "PPM5.0"
    ppm10_sensor:
      name: "PPM10"
    update_interval: 10s