views:
  - title: Home
    cards:
      - type: weather-forecast
        entity: weather.forecast_home
        forecast_type: daily
      - type: custom:hourly-weather
        entity: weather.forecast_home
        icons: true
        show_wind: speed
        show_precipitation_probability: true
        show_precipitation_amounts: true
        name: ' '
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: Temperature
            entities:
              - sensor.air_master_temperature
            line_width: 8
            font_size: 65
            animate: true
            smoothing: true
            align_state: center
            show:
              icon_adaptive_color: true
            color_thresholds:
              - value: 21.5
                color: '#0000ff'
              - value: 22
                color: '#00ffff'
              - value: 22.5
                color: '#00ff00'
              - value: 23
                color: '#ffff00'
              - value: 23.5
                color: '#ff8800'
              - value: 24
                color: '#ff0000'
          - type: custom:mini-graph-card
            name: Humidity
            entities:
              - sensor.air_master_humidity
            line_width: 8
            font_size: 65
            animate: true
            smoothing: true
            align_state: center
            show:
              icon_adaptive_color: true
            color_thresholds:
              - value: 45
                color: '#ff0000'
              - value: 48
                color: '#ff8800'
              - value: 51
                color: '#ffff00'
              - value: 54
                color: '#00ff00'
              - value: 57
                color: '#00ffff'
              - value: 60
                color: '#0000ff'
          - type: custom:mini-graph-card
            name: CO2
            entities:
              - sensor.air_master_co2
            line_width: 8
            font_size: 65
            animate: true
            smoothing: true
            align_state: center
            show:
              icon_adaptive_color: true
            color_thresholds:
              - value: 400
                color: '#0000ff'
              - value: 600
                color: '#00ffff'
              - value: 800
                color: '#00ff00'
              - value: 1000
                color: '#ffff00'
              - value: 1200
                color: '#ff8800'
              - value: 1400
                color: '#ff0000'
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            name: HCHO
            entities:
              - sensor.air_master_hcho
            line_width: 8
            font_size: 65
            animate: true
            smoothing: true
            align_state: center
            show:
              icon_adaptive_color: true
            color_thresholds:
              - value: 30
                color: '#0000ff'
              - value: 40
                color: '#00ffff'
              - value: 50
                color: '#00ff00'
              - value: 60
                color: '#ffff00'
              - value: 70
                color: '#ff8800'
              - value: 80
                color: '#ff0000'
          - type: custom:mini-graph-card
            name: PM2.5
            entities:
              - sensor.air_master_pm2_5
            line_width: 8
            font_size: 65
            animate: true
            smoothing: true
            align_state: center
            show:
              icon_adaptive_color: true
            color_thresholds:
              - value: 0
                color: '#0000ff'
              - value: 10
                color: '#00ffff'
              - value: 20
                color: '#00ff00'
              - value: 30
                color: '#ffff00'
              - value: 40
                color: '#ff8800'
              - value: 50
                color: '#ff0000'
          - type: custom:mini-graph-card
            name: PM10
            entities:
              - sensor.air_master_pm10
            line_width: 8
            font_size: 65
            animate: true
            smoothing: true
            align_state: center
            show:
              icon_adaptive_color: true
            color_thresholds:
              - value: 10
                color: '#0000ff'
              - value: 20
                color: '#00ffff'
              - value: 30
                color: '#00ff00'
              - value: 40
                color: '#ffff00'
              - value: 50
                color: '#ff8800'
              - value: 60
                color: '#ff0000'
